### ISSUE TITLE
Calculate motif enrichment

### ISSUE THREAD

**Issue by mzavolan** [zavolanlab/htsinfer#14]
Given two dictionaries of motif counts (foreground and background), calculate the enrichment (ratio of the probabilities of occurrence of the motif in foreground and background) and p-value (assuming binomial sampling with average frequency taken from the background set) for all motifs in the foreground set. Return these as a dictionary.

**Comment by PaulRitsche** [comment]
Hi everybody, 

if possible, I'd like to work on this issue.

**Comment by uniqueg** [comment]
Thanks @PaulRitsche, assigned you

**Comment by PaulRitsche** [comment]
Thanks!

**Comment by PaulRitsche** [comment]
@uniqueg 
Am I correct to assume that the motif counts in the two dictionaries are strings (of a given length, the foreground dictionary is "given", the background dictionary is a random sample of the whole data set and the returned dictionary must contain the motifs of the foreground set as keys and their respective enrichment and p-values as values? 
I don't have a biology background, excuse my basic question. Thanks for the help!

**Comment by mzavolan** [comment]
Motifs are strings, the dictionaries have motifs as keys and counts as values. The dictionaries of motif counts in foreground and background are input parameters to the function and your assumption about the return value is correct.

**Comment by PaulRitsche** [comment]
Thanks for the help! 
One further question: Are the two dictionaries inputted as files or in a variable?

**Comment by PaulRitsche** [comment]
Hi everybody, 

i don't think that I'll be able to finish the assignment today. However, if it's fine by you, I'd like to keep working on it and finish it. 
Is there a specific way that you have in mind to calculate the p-value for the motif?

**Comment by mzavolan** [comment]
Sure, go ahead! For the p-value, use the binomial distribution, as described.

**Comment by PaulRitsche** [comment]
Thanks!

**Comment by PaulRitsche** [comment]
Hi everybody, 

**Here's the signature of my function for you to take a look at:**

Calculates enrichment and p-values of motifs with similar lengths.
Args: foreground: dictionary of motifs with counts
background: dictionary of motifs with counts
Returns: Dictionary including motifs, enrichment score and p-value.
Example: 
foreground = {"UGAUUC": 5, "UAAACC": 3, "AAGUUACCU": 1, "AAGCCUU": 1, "AGUUCUA": 1, "UUUCCCG": 5} 
background = {"UGAUUC": 3, "UAAACC": 5, "AAGCCUUAU": 1, "AGUUCUA": 1, "UUUCCCG": 5, "UUGGAA": 7}
>>> motifEnrichment(foreground, background)
    {'UGAUUC': [0.7333333333333334, 0.01646090534979423],
    'UAAACC': [0.7333333333333334, 0.21947873799725662],
    'AAGUUACCU': [1.375, 0.26337448559670795],
    'AAGCCUU': [1.6041666666666667, 0.26337448559670795],
    'AGUUCUA': [1.6041666666666667, 0.26337448559670795],
    'UUCCCG': [1.6041666666666667, 0.01646090534979423]}

**And here's how I'd like to proceed:**

1. Calulate sum of motifs of same length in dictionary
2. Calculate probability of occurrence of motifs for motifs of same length in dictionary
-> for foreground and background dictionary

3. Calculate enrichment for foreground motifs 
4. Calculate p-value for foreground motifs using binomial distribution 
5. Create dictionary containing enrichment and p-values

I'll hopefully finish this issue within this week, so that I can start working on my own project afterwards. 
Thank's for your feedback.

**Comment by mzavolan** [comment]
The plan looks good, though the enrichment/p-values in the example don't look right to me.

**Comment by PaulRitsche** [comment]
Maybe I calculated them wrong. Here are the formulas I used: 
probability of occurrence = sum of motifs with similar length / sum of motif counts
enrichment (of motifs with same length) = probability of occurrence foreground / probability of occurrence background 
p-value = binom.pmf(r = motif count, n = len(forward dictionary), p = average of occurrence probability of motifs in background dictionary)

**Comment by mzavolan** [comment]
You would need to calculate the probability of observing at least as many occurrences as you see in the foreground given the frequency in the background. So you would need to calculate the cumulative density function (1-binom.cdf(r, n, p)).

**Comment by PaulRitsche** [comment]
All right, I'll replace the p-value calculation with the cumulative density function, run the test and file a pull request.

**Comment by uniqueg** [comment]
Closing this for now as we chose to implement a brute force algorithm for 3' adapter extraction for the meantime.
