### ISSUE TITLE
Infer organism from fastQ sample: Selecting Genes

### ISSUE THREAD

**Issue by rohank63** [zavolanlab/htsinfer#9]
The goal here is to identify which genes to pick, in order to map them across the fastQ reads which will determine the type of organism from the derived samples.

Selection of Genes are being done on the following factors:

- Genes which are universally conserved across some organisms.
- Genes that are highly expressed among organisms.
- Most abundant Ribosomal Proteins :
- One Ribosomal RNA
- One protein coding gene.

**Comment by uniqueg** [comment]
Mihaela suggested to use a set of ribosomal proteins, perhaps a dozen. The more genes we have, the more confident our inference will be. Ribosomal proteins are generally highly conserved and are expressed at pretty high levels. So perhaps you could find out what are the most abundant ribosomal proteins in two or three organisms (human, mouse, yeast) and then we use those. Ribosomal RNAs we should probably still include as well.

**Comment by uniqueg** [comment]
So in other words: instead of one protein-coding gene, we will take 10 or 12 or so.

**Comment by rohank63** [comment]
#### Abundant Ribosomal Proteins :
### Saccharomyces cerevisiae

> ### RPS0A, RPS0B, RPS2, RPS3, RPS1A, RPS1B, RPS4A, RPS4B, RPS5, RPS6A, RPS6B, RPS7A, RPS7B, RPS8A, RPS8B 

### Homo Sapiens

> ### RPSA, RPS2, RPS3, RPS3A, RPS4X, RPS4Y1, RPS5, RPS6, RPS7, RPS8, RPS9, RPS10, RPS11, RPS12, RPS13

**Comment by uniqueg** [comment]
Thanks - that's good! However, as we will need them for several organisms (probably >100, see #10), we need to find a more sustainable strategy. Basically, what we need is some conservation map including as many organisms as we can get. Please have a look

**Comment by uniqueg** [comment]
Probably the way to go here is to use [BioMart](https://m.ensembl.org/info/data/biomart/index.html). You will need to choose one of the options that give your programmatic access, e.g., the R/Bioconductor option or the RESTful API. With BioMart, you should be able to choose an organism and a gene (e.g., Saccharomyces cerevisiae -> RPS2) and then retrieve the names of the orthologs in _other_ species. The problem is that there's BioMart for fungi, protists, metazoa, bacteria..., so you will likely need multiple rounds. And while you're at it, you might do that for all organisms that are available in Ensembl. Then you can also use BioMart to actually retrieve the transcript sequences (there may be multiple) of each orthologue of the different ribosomal protein genes, as well as ribosomal RNA genes. These need to be concatenated into a single FASTA file with the organism name and gene ID as identifier for each sequence (e.g., `> Saccharomyces_cerevisiae.RPS2.transcript_X`).

**Comment by rohank63** [comment]
Hi @uniqueg , I am using R/Bioconductor to  retrieve the names of the orthologs in other species. Let's say I am finding the orthologs for RPSA ribosomal protein gene of Human, while doing so I have a list of attributes, that I can use to display in the file. 
#### Example: %id. target, %id. query, Gene-order conservation score, Whole-genome alignment coverage, confidence score.
```
Species               Target %id   Query %id    Gene-order conservation score   ....   ....  
Bonobo (Pan paniscus) 100.00%      98.33%        100  
Common carp hebao red 100.00%      40.33%          0
Gorilla               100.00%      98.33%         50
```

Perhaps, you can tell me if you need any more attribute along with species name. Once it is clear, I can do for rest of the Genes , and later for  fungi, protists, metazoa, bacteria as well.
